import 'package:get/get.dart';

class Localization extends Translations {
  @override
  Map<String, Map<String, String>> get keys => {
    'en': {
      'auth.signInButton': 'Sign In',
      'auth.signUpButton': 'Sign Up',
      'auth.resetPasswordButton': 'Send Password Reset',
      'auth.emailFormField': 'Email',
      'auth.passwordFormField': 'Password',
      'auth.nameFormField': 'Name',
      'auth.signInErrorTitle': 'Sign In Error',
      'auth.signInError': 'Login failed: email or password incorrect.',
      'auth.resetPasswordLabelButton': 'Forgot password?',
      'auth.signUpLabelButton': 'Create an Account',
      'auth.signUpErrorTitle': 'Sign Up Failed.',
      'auth.signUpError': 'There was a problem signing up.  Please try again later.',
      'auth.signInLabelButton': 'Have an Account? Sign In.',
      'auth.resetPasswordNoticeTitle': 'Password Reset Email Sent',
      'auth.resetPasswordNotice': 'Check your email and follow the instructions to reset your password.',
      'auth.resetPasswordFailed': 'Password Reset Email Failed',
      'auth.signInonResetPasswordLabelButton': 'Sign In',
      'auth.updateUser': 'Update Profile',
      'auth.updateUserSuccessNoticeTitle': 'User Updated',
      'auth.updateUserSuccessNotice': 'User information successfully updated.',
      'auth.updateUserEmailInUse': 'That email address already has an account.',
      'auth.updateUserFailNotice': 'Failed to update user',
      'auth.enterPassword': 'Enter your password',
      'auth.cancel': 'Cancel',
      'auth.submit': 'Submit',
      'auth.changePasswordLabelButton': 'Change Password',
      'auth.resetPasswordTitle': 'Reset Password',
      'auth.updateProfileTitle': 'Update Profile',
      'auth.wrongPasswordNoticeTitle': 'Login Failed',
      'auth.wrongPasswordNotice': 'The password does not match our records.',
      'auth.unknownError': 'Unknown Error',
      'settings.title': 'Settings',
      'settings.language': 'Language',
      'settings.theme': 'Theme',
      'settings.signOut': 'Sign Out',
      'settings.dark': 'Dark',
      'settings.light': 'Light',
      'settings.system': 'System',
      'settings.updateProfile': 'Update Profile',
      'home.title': 'Home',
      'home.nameLabel': 'Name',
      'home.uidLabel': 'UID',
      'home.emailLabel': 'Email',
      'home.adminUserLabel': 'Admin User',
      'app.title': 'Flutter Starter Project',
      'validator.email': 'Please enter a valid email address.',
      'validator.password': 'Password must be at least 6 characters.',
      'validator.name': 'Please enter a name.',
      'validator.number': 'Please enter a number.',
      'validator.notEmpty': 'This is a required field.',
      'validator.amount': 'Please enter a number i.e. 250 - no dollar symbol and no cents',
      'speech.error': "There's an error occurred on Speech recognition function",
      'speech.comment' : "Click mic icon and say something."
      },
    'ko': {
      'auth.signInButton': '로그인',
      'auth.signUpButton': '회원가입',
      'auth.resetPasswordButton': '초기화 하기',
      'auth.emailFormField': '이메일',
      'auth.passwordFormField': '비밀번호',
      'auth.nameFormField': '이름',
      'auth.signInErrorTitle': '로그인 오류',
      'auth.signInError': '로그인 실패 : 이메일이나 비밀번호가 올바르지 않습니다.',
      'auth.resetPasswordLabelButton': '비밀번호를 잊어버리셨나요?',
      'auth.signUpLabelButton': '회원 가입하기',
      'auth.signUpErrorTitle': '회원가입 실패',
      'auth.signUpError': '회원가입에 실패하였습니다. 잠시 후 다시 시도해주세요',
      'auth.signInLabelButton': '로그인 하기',
      'auth.resetPasswordNoticeTitle': '초기화 메일이 전송되었습니다.',
      'auth.resetPasswordNotice': '비밀번호 초기화를 위한 이메일을 다시 한 번 확인해주세요.',
      'auth.resetPasswordFailed': '비밀번호 초기화에 실패하였습니다.',
      'auth.signInonResetPasswordLabelButton': '로그인',
      'auth.updateUser': '회원정보 수정',
      'auth.updateUserSuccessNoticeTitle': '회원정보 수정됨',
      'auth.updateUserSuccessNotice': 'И회원님의 정보가 성공적으로 수정되었습니다..',
      'auth.updateUserEmailInUse': '입력하신 이메일은 이미 사용 중입니다.\n 회원이시라면 로그인 하여주세요.',
      'auth.updateUserFailNotice': '회원정보 수정에 실패하였습니다.',
      'auth.enterPassword': '비밀번호를 입력 하십시오',
      'auth.cancel': '취소',
      'auth.submit': '확인',
      'auth.changePasswordLabelButton': '비밀번호 변경',
      'auth.resetPasswordTitle': '비밀번호 초기화',
      'auth.updateProfileTitle': '프로필 수정',
      'auth.wrongPasswordNoticeTitle': '로그인 실패',
      'auth.wrongPasswordNotice': '비밀번호가 일치하지 않습니다.',
      'auth.unknownError': '알 수 없는 오류',
      'settings.title': '설정',
      'settings.language': '언어',
      'settings.theme': '테마',
      'settings.signOut': '로그아웃',
      'settings.dark': '어둡게',
      'settings.light': '밝게',
      'settings.system': '시스템',
      'settings.updateProfile': '프로필 수정',
      'home.title': '홈 화면',
      'home.nameLabel': '이름',
      'home.uidLabel': 'UID',
      'home.emailLabel': '이메일',
      'home.adminUserLabel': '관리자',
      'app.title': '플러터 초기 프로젝트',
      'validator.email': '올바른 이메일 양식을 입력해주세요.',
      'validator.password': '비밀번호는 6자리 이상만 입력 가능합니다.',
      'validator.name': '이름을 입력해 주세요.',
      'validator.number': '숫자를 입력해 주세요.',
      'validator.notEmpty': '이 항목은 필수 입력란입니다.',
      'validator.amount': '특수기호 없이 숫자만 입력해주세요.',
      'speech.error': '음성인식 기능에 오류가 발생하였습니다.',
      'speech.comment': '마이크 버튼을 눌러 말씀하세요.'
    },
        };
      }
      