import 'package:get/get.dart';

class Localization extends Translations {
  @override
  Map<String, Map<String, String>> get keys => {
        'en': {
          'auth.signInButton': 'Sign In',
          'auth.signUpButton': 'Sign Up',
          'auth.resetPasswordButton': 'Send Password Reset',
          'auth.emailFormField': 'Email',
          'auth.passwordFormField': 'Password',
          'auth.nameFormField': 'Name',
          'auth.signInErrorTitle': 'Sign In Error',
          'auth.signInError': 'Login failed: email or password incorrect.',
          'auth.resetPasswordLabelButton': 'Forgot password?',
          'auth.signUpLabelButton': 'Create an Account',
          'auth.signUpErrorTitle': 'Sign Up Failed.',
          'auth.signUpError':
              'There was a problem signing up.  Please try again later.',
          'auth.signInLabelButton': 'Have an Account? Sign In.',
          'auth.resetPasswordNoticeTitle': 'Password Reset Email Sent',
          'auth.resetPasswordNotice':
              'Check your email and follow the instructions to reset your password.',
          'auth.resetPasswordFailed': 'Password Reset Email Failed',
          'auth.signInonResetPasswordLabelButton': 'Sign In',
          'auth.updateUser': 'Update Profile',
          'auth.updateUserSuccessNoticeTitle': 'User Updated',
          'auth.updateUserSuccessNotice':
              'User information successfully updated.',
          'auth.updateUserEmailInUse':
              'That email address already has an account.',
          'auth.updateUserFailNotice': 'Failed to update user',
          'auth.enterPassword': 'Enter your password',
          'auth.cancel': 'Cancel',
          'auth.submit': 'Submit',
          'auth.changePasswordLabelButton': 'Change Password',
          'auth.resetPasswordTitle': 'Reset Password',
          'auth.updateProfileTitle': 'Update Profile',
          'auth.wrongPasswordNoticeTitle': 'Login Failed',
          'auth.wrongPasswordNotice':
              'The password does not match our records.',
          'auth.unknownError': 'Unknown Error',
          'settings.title': 'Settings',
          'settings.language': 'Language',
          'settings.theme': 'Theme',
          'settings.signOut': 'Sign Out',
          'settings.dark': 'Dark',
          'settings.light': 'Light',
          'settings.system': 'System',
          'settings.updateProfile': 'Update Profile',
          'home.title': 'Home',
          'home.nameLabel': 'Name',
          'home.uidLabel': 'UID',
          'home.emailLabel': 'Email',
          'home.adminUserLabel': 'Admin User',
          'app.title': 'Flutter Starter Project',
          'validator.email': 'Please enter a valid email address.',
          'validator.password': 'Password must be at least 6 characters.',
          'validator.name': 'Please enter a name.',
          'validator.number': 'Please enter a number.',
          'validator.notEmpty': 'This is a required field.',
          'validator.amount':
              'Please enter a number i.e. 250 - no dollar symbol and no cents',
          'speech.error':
              "There's an error occurred on Speech recognition function",
          'speech.comment': "Click mic icon and say something.",
          'title.guilt' : 'How to Eliminate Guilt',
          'close': 'close',
          'solution.over10.guilt':"Everyone experiences guilt at one time or another during their life. Guilt is a feeling of responsibility for something bad or wrong. Guilt has various sources. For example, it may come from thinking that you have done something wrong, caused someone harm or did nothing when you should have acted. It can also come from a sense that you have succeeded when others have failed, as in the case of survivor's guilt. Guilt is not always a bad thing, since it often promotes remorse, changes in future behavior, and feelings of empathy. At the same time, however, guilt can become a problem when it is unproductive and does not help change behavior but instead causes a guilt-and-shame cycle."
        },
        'ko': {
          'auth.signInButton': '로그인',
          'auth.signUpButton': '회원가입',
          'auth.resetPasswordButton': '초기화 하기',
          'auth.emailFormField': '이메일',
          'auth.passwordFormField': '비밀번호',
          'auth.nameFormField': '이름',
          'auth.signInErrorTitle': '로그인 오류',
          'auth.signInError': '로그인 실패 : 이메일이나 비밀번호가 올바르지 않습니다.',
          'auth.resetPasswordLabelButton': '비밀번호를 잊어버리셨나요?',
          'auth.signUpLabelButton': '회원 가입하기',
          'auth.signUpErrorTitle': '회원가입 실패',
          'auth.signUpError': '회원가입에 실패하였습니다. 잠시 후 다시 시도해주세요',
          'auth.signInLabelButton': '로그인 하기',
          'auth.resetPasswordNoticeTitle': '초기화 메일이 전송되었습니다.',
          'auth.resetPasswordNotice': '비밀번호 초기화를 위한 이메일을 다시 한 번 확인해주세요.',
          'auth.resetPasswordFailed': '비밀번호 초기화에 실패하였습니다.',
          'auth.signInonResetPasswordLabelButton': '로그인',
          'auth.updateUser': '회원정보 수정',
          'auth.updateUserSuccessNoticeTitle': '회원정보 수정됨',
          'auth.updateUserSuccessNotice': 'И회원님의 정보가 성공적으로 수정되었습니다..',
          'auth.updateUserEmailInUse':
              '입력하신 이메일은 이미 사용 중입니다.\n 회원이시라면 로그인 하여주세요.',
          'auth.updateUserFailNotice': '회원정보 수정에 실패하였습니다.',
          'auth.enterPassword': '비밀번호를 입력 하십시오',
          'auth.cancel': '취소',
          'auth.submit': '확인',
          'auth.changePasswordLabelButton': '비밀번호 변경',
          'auth.resetPasswordTitle': '비밀번호 초기화',
          'auth.updateProfileTitle': '프로필 수정',
          'auth.wrongPasswordNoticeTitle': '로그인 실패',
          'auth.wrongPasswordNotice': '비밀번호가 일치하지 않습니다.',
          'auth.unknownError': '알 수 없는 오류',
          'settings.title': '설정',
          'settings.language': '언어',
          'settings.theme': '테마',
          'settings.signOut': '로그아웃',
          'settings.dark': '어둡게',
          'settings.light': '밝게',
          'settings.system': '시스템',
          'settings.updateProfile': '프로필 수정',
          'home.title': '홈 화면',
          'home.nameLabel': '이름',
          'home.uidLabel': 'UID',
          'home.emailLabel': '이메일',
          'home.adminUserLabel': '관리자',
          'app.title': '플러터 초기 프로젝트',
          'validator.email': '올바른 이메일 양식을 입력해주세요.',
          'validator.password': '비밀번호는 6자리 이상만 입력 가능합니다.',
          'validator.name': '이름을 입력해 주세요.',
          'validator.number': '숫자를 입력해 주세요.',
          'validator.notEmpty': '이 항목은 필수 입력란입니다.',
          'validator.amount': '특수기호 없이 숫자만 입력해주세요.',
          'speech.error': '음성인식 기능에 오류가 발생하였습니다.',
          'speech.comment': '마이크 버튼을 눌러 말씀하세요.',
          'title.guilt' : '죄책감 떨쳐내기',
          //  10점 이상
          'solution.over10.guilt':
              '죄책감은 모든 사람이 언젠가는 한 번쯤은 경험하는 자연스러운 인간적인 감정이다.\n 하지만 많은 사람들은 극심한 또는 만성적인 자책감이나 수치심 때문에 큰 스트레스를 받기도 한다. \n합리적인 죄책감이란 타인이 자신의 행동, 결정 기타 잘못에 의해 부정적으로 영향을 받아 이에 책임을 져야 할 때 느끼는 죄책감이다. \n이는 건강한 죄책감으로, 잘못한 점을 고치도록 장려하여, 친밀감을 조성하며, 공통된 책임감을 느끼게 할 수 있다. \n한편, 불필요한 죄책감이란, 다른 사람의 행동이나 삶, 자신이 통제 할 수 없는 것 그리고 대부분의 상황에서 발생하는 여파와 같이 자신이 책임 질 수 없는 것들에 대한 죄책감이다. \n이러한 종류의 죄책감은 우리로 하여금 인지한 실패에 대해 곱씹게 하여, 수치심과 억울한 마음을 불러일으킨다. \n당신의 죄책감이 과거의 잘못에서 비롯된 것이건, 우연히 발생한 것이건 간에 이 감정을 해소 할 수 있는 방법이 있다.',
          'solution.over10.suicide':
              '절망감, 고립감, 고통이 너무 심해져서 더 이상 견디기가 힘들다면 머릿속에 계속해서 자살에 대한 생각이 떠오르고 자살만이 남은 길이라는 믿음을 가질 수도 있다. \n물론 지금은 심신이 지쳐서 보이지 않을 수도 있겠지만, 세상에는 당신이 인식하고 있지 못한 즐거움, 사랑, 자유가 있다. \n당신에게 안심감과 생기를 불어넣어 이 모든 긍정적인 것들을 누리게 해줄 선택지들이 있다. \n이 글에서는 가장 먼저 현재 당신의 안전을 보장한 뒤, 미래를 위한 대처법과 자살 충동의 원인을 분석해보는 시간을 가지도록 하겠다. \n이 과정을 당신의 기분이 나아질 때까지 지속해야 한다는 사실도 기억하도록 하자.',
          'solution.over10.pessimism':
              '주변에 비관주의자가 있는가? 긍정적인 면보다는 부정적인 면을 생각하는 사람 말이다. 낙천적이고 발랄한 사람은 비관주의자의 생각을 이해하기 어려울 수도 있다. 컵에 물이 절반만 있다고 투덜거리는 사람 때문에 우울해지지 않으려면 비관주의가 미치는 영향을 줄이고 긍정적이지 못한 생각을 가진 사람과 효과적으로 소통하고 비관주의에 대해 스스로 공부한다.',
          'solution.over10.worthlessness':
              '내가 나를 대하는 자세를 되돌아보는 것만큼 내가 남을 대하는 자세를 생각해 볼 필요가 있습니다. \n우리는 평소에 주변 사람들을 ‘있는 그대로’ 인정하고 있을까요? 책에서는 타인이 어떤 결정을 하던 간에 그것을 믿고 존중해 주는 것만큼 그 사람에게 힘을 실어주는 방법은 없다고 말합니다.\n 물론 올바른 방향이 아니라면 조언을 해 줄 수 있겠죠. 그 과정에서 상대를 깎아내리는 것은 절대 좋은 방법이 아닐 것입니다.',
          'solution.over10.self-dislike':
              '자기를 혐오하는 사람들은 타인에게는 쉽게 연민이나 동정심을 보이지만 자신에게 연민을 보이는 일은 쉽지 않아 하는 경향이 있다. \n이 부류의 사람들은 내면의 비판적인 목소리에만 집중하기 때문에 자신에게 친절하게 대해본 적이 없으며 자기 연민이라는 감정에 혼란스러워 한다.\n따라서 이해심을 가지고 자신의 실패와 단점을 받아들이는 법을 배워야 한다.',
          'solution.over10.self-criticism':
              '지나치고 빈번한 자기비판은 자기 태만의 한 형태이다. 자신을 비판함으로써 건강하지 못한 행동을 한다. \n그렇다면 왜 그러는 것일까? 거부, 두려움, 억압 등 우리를 누르는 것들에 익숙해져 있기 때문이다. \n이것은 부정성이 빠져나올 수 없는 함정이 되는 방법이다. 부정적인 것에 익숙하기 때문에 사슬로 묶어버리고 우리를 집어 삼킨다. \n부정성을 가지지 않으면 벌거벗은 것처럼 느끼기 때문에 기본적으로 부정적인 시각을 가진다.자기비판을 멈추고 싶다면 자신을 더 잘 알아야 한다. \n또한, 자신의 내면에서 일어나는 대화 습관도 바꾸어볼 필요가 있다.',
          'solution.over10.past-failure':
              '실패를 이겨내는 것은 자신에 대해 이해하는 것에서부터 시작된다. 먼저 해야 할 것은 실패했을 때 느끼는 감정을 극복하는 것이다. \n인간 관계, 연애, 일을 포함한 다른 목표에서 실패하는 것은 당신을 어쩔 줄 모르게 할 수 있지만, 당신이 실패로 인한 실망감과 자신의 실수를 포용한다면 기죽지 않고 다음 발걸음을 내딛을 수 있게 될 것이다. \n이런 현실적인 낙관주의를 통해 실패를 극복하고 다시 계획을 세워 인생의 다음 발걸음을 내딛는 방법을 이 글에서 배워볼 것이다. 또한 다음 문장을 명심하도록 하자. "인생의 궁극적인 목표는 회복력을 지니는 것이다. \n적응하고 번창하는 것이다. 자신의 실수로부터 경험을 쌓고 발전해나가야 한다',
          'solution.over10.punishment-feeling':
              '죄책감은 당신이 앞으로 나아가는 것을 막는 우울한 감정이다. 죄책감을 느끼게 되면 스스로 부정적인 감정을 막는 법과 과거의 행동에 대한 대처법을 이해하기 힘들다고 느낄 수도 있다. \n이 글을 통해 죄책감을 극복하는 방법을 배워 긍정적인 미래로 한 발을 내딛어보자. ',
          'cause.over10.guilt': '완벽주의적인 성향',
          'cause.over10.suicide': '자기 절제력 부족',
          'cause.over10.pessimism': '비관적인 사고',
          'cause.over10.worthlessness': '지나친 욕심',
          'cause.over10.self-dislike': '자기애 부족',
          'cause.over10.self-criticism': '부정적인 언행',
          'cause.over10.past-failure': '정신적 트라우마',
          'cause.over10.punishment-feeling': '지나친 자기관리',
          'close': '닫기'
        },
      };
}
